FROM maven:3.9.6-openjdk-17-slim AS build

# Set the working directory in the container
WORKDIR /app

# Copy the files file into the container at /app
COPY . .

# Build the application
RUN mvn clean package

# Use AdoptOpenJDK as a base image for running the application
FROM adoptopenjdk:17-jdk-hotspot AS runtime

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file from the build stage to the runtime stage
COPY --from=build /app/target/*.jar app.jar

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "app.jar"]
